apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  containers:
  - image: mariadb
    name: db
    envFrom:
      - configMapRef:
          name: dbcm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
