apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wp
  name: wp
spec:
  containers:
  - image: wordpress
    name: wp
    envFrom:
      - configMapRef:
          name: wpcm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
